version: '3.9'
services:
    development:
        build:
            context: ./
            dockerfile: Dockerfile
            target: development
        ports:
            - '5173:5173'
        networks:
            - internal
        develop:
            watch:
                - action: sync
                  path: ./
                  target: /app
                  ignore:
                      - ./node_modules
                      - ./.git
                      - ./.vscode
                      - ./package*.json
                - action: rebuild
                  path: ./package.json
        depends_on:
            npm:
                condition: service_completed_successfully

    npm:
        image: node:20-alpine
        user: 1000:1000
        working_dir: /code
        command: npm install
        networks:
            - internal
        volumes:
            - ./:/code

networks:
    internal:
        driver: bridge
