version: '3'
services:
    development:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
            args:
                WWWUSER: 1000
                WWWGROUP: 1000
        volumes:
            - ./:/app

        ports:
            - '5173:5173'
        networks:
            - internal

networks:
    internal:
        driver: bridge
