version: '3'
services:
    development:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        ports:
            - '5173:5173'
        networks:
            - internal
        develop:
            watch:
                - action: sync
                  path: ./
                  target: /app
                  ignore:
                      - node_modules/
                      - .git/
                - action: rebuild
                  path: package*.json

networks:
    internal:
        driver: bridge
